# Generated by Django 3.2.12 on 2022-06-23 19:36

from django.db import migrations, models
import psybot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot_conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_session_id', models.CharField(default='', max_length=500)),
                ('user_id', models.IntegerField(null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('input_text', models.TextField(default='')),
                ('response_text', models.JSONField(blank=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('next_response', models.JSONField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bot_sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_session_id', models.CharField(default='', max_length=500)),
                ('user_id', models.IntegerField(null=True)),
                ('category_id', models.IntegerField(null=True)),
                ('is_repeat_session', models.IntegerField(null=True)),
                ('device_type', models.CharField(default='', max_length=15)),
                ('http_referer', models.CharField(default='', max_length=30)),
                ('utm_source', models.CharField(default='', max_length=12)),
                ('utm_campaign', models.CharField(default='', max_length=20)),
                ('utm_content', models.CharField(default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.IntegerField(null=True)),
                ('exercise_name', models.CharField(default='', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_exercise_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.CharField(default='', max_length=50)),
                ('bot_session_id', models.CharField(default='', max_length=500)),
                ('completion_status', models.IntegerField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(null=True)),
                ('name', models.CharField(default='', max_length=225)),
                ('gender', models.CharField(default='', max_length=225)),
                ('age', models.IntegerField(null=True)),
                ('country', models.CharField(default='', max_length=225)),
                ('state', models.CharField(default='', max_length=225)),
                ('city', models.CharField(default='', max_length=225)),
                ('language', models.CharField(default='', max_length=225)),
                ('severity', models.CharField(default='', max_length=225)),
                ('cat_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, default='', max_length=50)),
                ('email', models.CharField(max_length=225, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', psybot.models.UserManager()),
            ],
        ),
    ]
