# Generated by Django 3.2.12 on 2022-06-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psybot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot_conversation',
            name='next_response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bot_conversation',
            name='input_text',
            field=models.TextField(default=''),
        ),
    ]
